import { z } from "zod";
import { OverlayPresetSchema, type OverlayPreset } from "@/lib/schema";

export const PresetRowSchema = z.object({
  id: z.string(),
  slot_index: z.number(),
  name: z.string(),
  version: z.number(),
  renderer: z.string(),
  anchor: z.string(),
  offset_x: z.number(),
  offset_y: z.number(),
  safe_margin_x: z.number(),
  safe_margin_y: z.number(),
  artist_font_family: z.string(),
  artist_font_size: z.number(),
  artist_weight: z.number(),
  title_font_family: z.string(),
  title_font_size: z.number(),
  title_weight: z.number(),
  text_align: z.string(),
  line_height: z.number(),
  letter_spacing: z.number(),
  max_lines_title: z.number(),
  color_artist: z.string(),
  color_title: z.string(),
  color_bg: z.string().nullable(),
  color_shadow: z.string().nullable(),
  card_enabled: z.boolean(),
  card_padding_x: z.number(),
  card_padding_y: z.number(),
  card_radius: z.number(),
  card_blur: z.number(),
  card_opacity: z.number(),
  fade_in_sec: z.number(),
  fade_out_sec: z.number(),
  anim_memo: z.string().nullable(),
  updated_at: z.string(),
});

export type PresetRow = z.infer<typeof PresetRowSchema>;

export function rowToPreset(row: PresetRow): OverlayPreset | null {
  const result = OverlayPresetSchema.safeParse({
    id: row.id,
    version: row.version,
    renderer: row.renderer,
    layout: {
      anchor: row.anchor,
      x: row.offset_x,
      y: row.offset_y,
      safeMarginX: row.safe_margin_x,
      safeMarginY: row.safe_margin_y,
    },
    typography: {
      artistFontFamily: row.artist_font_family,
      titleFontFamily: row.title_font_family,
      artistFontSize: row.artist_font_size,
      titleFontSize: row.title_font_size,
      artistWeight: row.artist_weight,
      titleWeight: row.title_weight,
      letterSpacing: row.letter_spacing,
      lineHeight: row.line_height,
      maxLinesTitle: row.max_lines_title,
      textAlign: row.text_align,
    },
    color: {
      artist: row.color_artist,
      title: row.color_title,
      background: row.color_bg ?? undefined,
      shadow: row.color_shadow ?? undefined,
    },
    card: {
      enabled: row.card_enabled,
      paddingX: row.card_padding_x,
      paddingY: row.card_padding_y,
      radius: row.card_radius,
      blur: row.card_blur,
      opacity: row.card_opacity,
    },
    animation: {
      fadeInSec: row.fade_in_sec,
      fadeOutSec: row.fade_out_sec,
      animMemo: row.anim_memo ?? undefined,
    },
  });
  return result.success ? result.data : null;
}

export function presetToRow(
  preset: OverlayPreset,
  slotIndex: number,
  name: string
): Omit<PresetRow, "updated_at"> {
  return {
    id: preset.id,
    slot_index: slotIndex,
    name,
    version: preset.version + 1,
    renderer: preset.renderer,
    anchor: preset.layout.anchor,
    offset_x: preset.layout.x,
    offset_y: preset.layout.y,
    safe_margin_x: preset.layout.safeMarginX,
    safe_margin_y: preset.layout.safeMarginY,
    artist_font_family: preset.typography.artistFontFamily,
    artist_font_size: preset.typography.artistFontSize,
    artist_weight: preset.typography.artistWeight,
    title_font_family: preset.typography.titleFontFamily,
    title_font_size: preset.typography.titleFontSize,
    title_weight: preset.typography.titleWeight,
    text_align: preset.typography.textAlign,
    line_height: preset.typography.lineHeight,
    letter_spacing: preset.typography.letterSpacing,
    max_lines_title: preset.typography.maxLinesTitle,
    color_artist: preset.color.artist,
    color_title: preset.color.title,
    color_bg: preset.color.background ?? null,
    color_shadow: preset.color.shadow ?? null,
    card_enabled: preset.card.enabled,
    card_padding_x: preset.card.paddingX,
    card_padding_y: preset.card.paddingY,
    card_radius: preset.card.radius,
    card_blur: preset.card.blur,
    card_opacity: preset.card.opacity,
    fade_in_sec: preset.animation.fadeInSec,
    fade_out_sec: preset.animation.fadeOutSec,
    anim_memo: preset.animation.animMemo ?? null,
  };
}
